services:
  jekyll:
    image: ruby:3.1-alpine
    ports:
      - "4001:4000"
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
    command: >
      sh -c "
        apk add --no-cache build-base &&
        gem install bundler jekyll &&
        bundle install &&
        bundle exec jekyll serve --host 0.0.0.0 --livereload --baseurl ''
      "